"""Changed title

Revision ID: 10dd5e8ebdc9
Revises: 0d8588c60c1e
Create Date: 2020-07-31 05:51:42.173902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dd5e8ebdc9'
down_revision = '0d8588c60c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_task_list', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_column('todo_task_list', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_task_list', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('todo_task_list', 'title')
    # ### end Alembic commands ###
